import Head from "next/head";
import { Inter } from "next/font/google";
import { useState, useEffect } from "react";
import Login from "@/components/Login";
import { UserContext } from "@/lib/context";
import Profile from "@/components/Profile";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [username, setUsername] = useState("");

  useEffect(() => {
    const user = window.localStorage.getItem('CFS_Content_Username');
    if (user !== "") setUsername(JSON.parse(user));
  }, []);

  return (
    <>
      <Head>
        <title>CFS Classroom Content Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserContext.Provider value={{ username, setUsername }}>
        <main className={inter.className}>
          <div className="m-8">{username ? <Profile /> : <Login />}</div>
        </main>
      </UserContext.Provider>
    </>
  );
}
